spring.application.name=bond-finance
<<<<<<< Updated upstream
=======

spring.threads.virtual.enabled=true

spring.datasource.url=jdbc:mysql://localhost:3306/BOND_FINANCE
spring.datasource.username=root
spring.datasource.password=Di537200218
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.batch.jdbc.initialize-schema=always
spinrg.batch.job.enabled=false

data.api.baseUrl=https://apis.data.go.kr
data.api.service-key=2516e9218ce989b263ccbddb18e1e48151f3dc4a1084adc06dcd5de2d482fdcf
>>>>>>> Stashed changes
