spring.application.name=bond-finance

spring.datasource.url=jdbc:mysql://localhost:3306/BOND_FINANCE
spring.datasource.username=root
spring.datasource.password=Di537200218
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.batch.jdbc.initialize-schema=always